spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/243848737/config-repo.git
          username: 243848737
          password: Bp666888
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 允许/actuator/bus-refresh接口被外部调用
management:
  endpoints:
    web:
      exposure:
        include: "*"