eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: peer2
    prefer-ip-address: false
server:
  port: 2222