eureka:
  client:
    service-url:
      defaultZone: http://peer2:2222/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: peer1
    prefer-ip-address: false
server:
  port: 1111